### ISSUE TITLE
ylim of EnhancedVolcano

### ISSUE THREAD

**Issue by tamerbio** [kevinblighe/EnhancedVolcano#105]
Hi,
thank you so much for this great function. is there any way to set ylim to scale_y_continuous(trans = "log1p")?
this will give an impressive volcanoplot.
thanks much

**Comment by kevinblighe** [comment]
Hi @tamerbio, I am not sure, as modifying the y-axis is quite difficult due to how much of the y-axis is manipulated internally. Perhaps you could try the example as given here, though: https://github.com/kevinblighe/EnhancedVolcano#custom-axis-tick-marks

Let me know if that helps. Please re-open the issue if you still require assistance. Unfortunately, I have no resources to further develop this package.

Kind regards,
Kevin
