### ISSUE TITLE
shape, colCustom and drawConnector arguments don't work

### ISSUE THREAD

**Issue by EmilieGllch** [kevinblighe/EnhancedVolcano#24]
Hello,

When I'm trying to use "shape", "colCustom" or "drawConnectors" arguments, I get an error "unused arguments".

Can you help me with this issue ?

Btw very nice package ! 

Thank you

Emilie

**Comment by kevinblighe** [comment]
Hey Emilie, thanks for your message. The package has undergone some development since it was first on Bioconductor (Fall, 2018). Many parameters have been added and some renamed (but backward compatibility is in place for the renamed ones).

You may be using an older version of the package and should therefore update. To obtain the most recent version with all new modifications, you can install the devel version via:

```
devtools::install_github('kevinblighe/EnhancedVolcano')
```

Which version are you using (type `sessionInfo()`)?

**Comment by EmilieGllch** [comment]
Hi,

I installed it today from bioconductor and the version is 1.0.1...
I tried to install devtools but I have an error message... so I can't install it using this command line... Is there another way to get the latest version ?

Thank you for your help !

Emilie

**Comment by kevinblighe** [comment]
I see, in that case, you must be using an old version of R, too (probably R3.5?) What was the error when you tried to install the development version? You may need to install the _devtools_ package with:

```
install.packages('devtools')
```
If you can also update your version of R to R 3.6, that would be great.

**Comment by EmilieGllch** [comment]
Yes indeed I had the R version 3.5. I made the update for 3.6 and reloaded the package from bioconductor and now I have version 1.2 in which the arguments work just fine :)

And I had no error trying to install the development version, my problem is that I could not install the package devtools... !

Thank you very much for your help !

Emilie
