### ISSUE TITLE
Omit arrow (drawConnectors)

### ISSUE THREAD

**Issue by kunstner** [kevinblighe/EnhancedVolcano#47]
Hi,
is it possible to omit the arrow  and draw just a line between the label and the actual data point?
Best,
 Axel

**Comment by kevinblighe** [comment]
Hey Axel, the answer is 'no', unfortunately! Is it urgent? - I can implement a fix and have it available in the development version before next Monday, if required.

**Comment by kunstner** [comment]
Hi @kevinblighe,
thanks for your quick reply. It's not very urgent, just a nice to have. If you could provide a fix in the development version it would be very nice.
Best,
 Axel

**Comment by kevinblighe** [comment]
Hey @kunstner , this has now been implemented. You'll have to install the GitHub version for now; otherwise, in a few days, it will be on the Bioconductor Devel branch (and official branch when the next version of Bioconductor is released).

An example here:
https://github.com/kevinblighe/EnhancedVolcano#over-ride-colouring-scheme-with-custom-key-value-pairs

The parameter to use is `arrowheads`.

I also added other new functionality, as emphasised here:
https://github.com/kevinblighe/EnhancedVolcano#shade-certain-variables
