### ISSUE TITLE
Issue with 'selectLab'

### ISSUE THREAD

**Issue by nbbarrientos** [kevinblighe/EnhancedVolcano#60]
Hello,

First off, thank you for this tool. Very useful and very easy to use. I have a question regarding 'selectLab'. Instead of genes, I'm plotting introns but I still chose to label these introns with the gene name they are part of. However, because there are multiple introns within a gene, I also see the same label printed out multiple times. This is okay, except that when I use the selectLab option, it also prints the labels for introns that are not significant. 

I was under the impression, based on the manual, that EnhancedVolcano will only print the labels for significant points (those that pass the -log10(p-value) and the log2(FC) thresholds) by default. Does selectLab override this when used? If so, is there a way to maintain the default printing of labels (to print only significant ones) when using selectLab?

Here's an example of what I'm getting:
![image](https://user-images.githubusercontent.com/62807501/94058169-b1f54700-fdae-11ea-89b3-65beb6be98a0.png)

Thank you so much for your help.
Nelson Barrientos

**Comment by kevinblighe** [comment]
Hi Nelson, Thank you for using this package.

Hmm, this problem is somewhat unique. Based on how the package is designed, when `selectLab` is activated, yes, it overrides the thresholds for -log10(p-value) and log2(FC).

In order to do what you want, unfortunately, you may have to manually change the names for the non-statistically significant introns for _VCAM1_ and _TPM2_. For example, change them [temporarily] to _VCAM1ns_ and _TPM2ns_

Kind regards,
Kevin

**Comment by nbbarrientos** [comment]
Hi Kevin,

Thank you for your quick response. I was thinking that might be the best course of action for now. 

Best regards,
Nelson
