### ISSUE TITLE
pinpointing the gene of interest

### ISSUE THREAD

**Issue by rocknrollscience** [kevinblighe/EnhancedVolcano#7]
Hi Kevin,

First of all thank you for this very useful script. I'm really new in terms of using R for analysis, so sorry in advance if I don't provide enough information. Basically I wanted to make a volcanoplot, only highlighting my gene of interest:

EnhancedVolcano(topTab, lab=rownames(topTab), x="logFC", y="adj.P.Val", selectLab = c("Hoxa9", "Meis1"), pCutoff = 0.05, FCcutoff = 2.0,  gridlines.major=FALSE, gridlines.minor=FALSE)

This worked fine and kind of did what I wanted. But the issue I had is, I couldn't pinpoint the exact dot of my genes (attached)

![rplot07](https://user-images.githubusercontent.com/19342224/52549466-5ec3c000-2e27-11e9-8496-136d8e700cf2.png)

I tried using the DrawConnectors=TRUE, 
EnhancedVolcano(topTab, lab=rownames(topTab), x="logFC", y="adj.P.Val", selectLab = c("Hoxa9", "Meis1"), pCutoff = 0.05, FCcutoff = 2.0, DrawConnectors = TRUE, widthConnectors = 5.0, colConnectors = "grey",  gridlines.major=FALSE, gridlines.minor=FALSE)

but no line connector appeared on the plot. Is there any other way around this?

![rplot08](https://user-images.githubusercontent.com/19342224/52549472-65523780-2e27-11e9-8c56-857650e23579.png)

Thanks!

**Comment by kevinblighe** [comment]
Hey, thank you for the comments. I had to look very close to see the gene labels! You may want to increase  the size of the font with transcriptLabSize.

Regarding the connectors, it is currently programmed to draw them only when space becomes limiting. So, if you are labeling, 50 genes, it will add connectors where necessary in order to utilise the most space possible. Note that, by increasing the transcriptLabSize, this may actually give you what you want because the labels of the 2 genes of interest will then clash.

My other recommendation for you is to install the development version via:

`  devtools::install_github('kevinblighe/EnhancedVolcano')`

The development version contains most recent updates and will eventually be on the official Bioconductor release schedule when that is updated. In particular, take a look at this example, which goes over how you could assign a different shape to your genes of interest, thus helping to identify them:
https://github.com/kevinblighe/EnhancedVolcano#over-ride-colour-andor-shape-scheme-with-custom-key-value-pairs

Kevin

**Comment by rocknrollscience** [comment]
Hi Kevin,

The development version looks like a charm. Managed to get a nice looking volcano plot! Awesome work! Thanks!

**Comment by kevinblighe** [comment]
Great! - thank you for the follow-up.
